### ISSUE TITLE
Multiple quality reports with different quality measures and specification

### ISSUE THREAD

**Issue by dgterritorio** [interactive-instruments/etf-webapp#138] opened 2017-10-23 18:12 UTC
When testing a metadata record with gmd:DQ_DomainConsistency  and regulation citation and another quality report with different quality measure and other specification citation, I get this error on "md.iso.a.5 Specification":

```
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'VetorRAA_CLC_2000.xml', record '5b0718ed-dda8-4e84-9627-8c12035cb229': The metadata record contains a reference to a specification 'Exatidão temática', but the specification reference is not a child of a gmd:DQ_DomainConsistency element.
```
When removing the other quality report (non INSPIRE), there are no errors.

Should be possíble to have different reports on the same quality section.

The metadata file that originated the error:
[VetorRAA_CLC_2000.zip](https://github.com/interactive-instruments/etf-webapp/files/1408281/VetorRAA_CLC_2000.zip)

**Comment by cportele** [comment] 2017-10-26 07:15
The issue is specific to the INSPIRE test suites, so I have copied the issue there: 

https://github.com/inspire-eu-validation/ets-repository/issues/115

I close the issue here.

**Closed by cportele** 2017-10-26 07:15 UTC
